"""bug_reports_table

Revision ID: 692e77190ace
Revises: stripe01
Create Date: 2026-07-22 18:00:42.552915
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '692e77190ace'
down_revision: Union[str, None] = 'stripe01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bug_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fix', sa.Text(), nullable=True),
    sa.Column('rule', sa.Text(), nullable=True),
    sa.Column('protection', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('reporter', sa.String(length=200), nullable=False),
    sa.Column('reporter_role', sa.String(length=50), nullable=True),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verification_comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_reports_bug_id'), 'bug_reports', ['bug_id'], unique=True)
    op.create_index(op.f('ix_bug_reports_status'), 'bug_reports', ['status'], unique=False)
    op.drop_table('alembic_version_marketing')
    op.drop_index(op.f('ix_action_requests_client_action_status'), table_name='action_requests')
    op.drop_index(op.f('ix_action_requests_client_status'), table_name='action_requests')
    op.drop_table('action_requests')
    op.drop_table('personas')
    op.drop_index(op.f('ix_analytics_events_type_timestamp'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_visitor_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_ab_test_assignments_test_variant'), table_name='ab_test_assignments')
    op.drop_index(op.f('ix_ab_test_assignments_visitor_id'), table_name='ab_test_assignments')
    op.drop_table('ab_test_assignments')
    op.drop_index(op.f('ix_waitlist_signups_created_at'), table_name='waitlist_signups')
    op.drop_index(op.f('ix_waitlist_signups_email'), table_name='waitlist_signups')
    op.drop_table('waitlist_signups')
    op.drop_index(op.f('ix_asc_avatar_subreddit'), table_name='avatar_subreddit_compatibility')
    op.drop_index(op.f('ix_asc_subreddit_score'), table_name='avatar_subreddit_compatibility')
    op.drop_table('avatar_subreddit_compatibility')
    op.create_index('ix_activity_events_client_created', 'activity_events', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_activity_events_type_created', 'activity_events', ['event_type', 'created_at'], unique=False)
    op.drop_index(op.f('ix_ai_usage_log_avatar_id'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_quality_outcome'), table_name='ai_usage_log')
    op.drop_index(op.f('ix_ai_usage_log_subreddit_name'), table_name='ai_usage_log')
    op.create_index('ix_ai_usage_log_client_created', 'ai_usage_log', ['client_id', 'created_at'], unique=False)
    op.create_index('ix_ai_usage_log_operation', 'ai_usage_log', ['operation'], unique=False)
    op.drop_index(op.f('ix_audit_log_client_action_created'), table_name='audit_log')
    op.alter_column('avatar_subreddit_bans', 'banned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('avatar_subreddit_bans', 'detection_evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('avatar_subreddit_bans', 'consecutive_deletions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('avatar_subreddit_bans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('avatar_subreddit_bans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_avatar_presence_avatar_activity'), table_name='avatar_subreddit_presence')
    op.create_index('ix_avatar_presence_avatar_activity', 'avatar_subreddit_presence', ['avatar_id', sa.literal_column('last_activity_at DESC')], unique=False)
    op.alter_column('avatars', 'delivery_channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'email'::character varying"))
    op.drop_index(op.f('ix_avatars_client_ids_gin'), table_name='avatars', postgresql_using='gin')
    op.drop_index(op.f('ix_avatars_pool'), table_name='avatars')
    op.alter_column('billing_period_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_csa_client_active_subreddit', 'client_subreddit_assignments', ['client_id', 'is_active', 'subreddit_id'], unique=False)
    op.drop_index(op.f('uq_client_subreddits_active_name'), table_name='client_subreddits', postgresql_where='(is_active = true)')
    op.alter_column('client_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('client_subscriptions_client_id_key'), 'client_subscriptions', type_='unique')
    op.drop_index(op.f('ix_client_subscriptions_client_id'), table_name='client_subscriptions')
    op.create_index(op.f('ix_client_subscriptions_client_id'), 'client_subscriptions', ['client_id'], unique=True)
    op.alter_column('clients', 'current_onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_comment_drafts_avatar_status_created'), table_name='comment_drafts')
    op.create_index('ix_comment_drafts_avatar_status', 'comment_drafts', ['avatar_id', 'status'], unique=False)
    op.create_index('ix_comment_drafts_client_status', 'comment_drafts', ['client_id', 'status'], unique=False)
    op.create_index('ix_comment_drafts_created_at', 'comment_drafts', ['created_at'], unique=False)
    op.create_index('ix_comment_drafts_status', 'comment_drafts', ['status'], unique=False)
    op.create_index('ix_comment_drafts_thread_pending', 'comment_drafts', ['thread_id'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.alter_column('decision_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_entities', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'extracted'::character varying"))
    op.alter_column('discovery_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_discovery_entities_session_id'), table_name='discovery_entities')
    op.alter_column('discovery_hypotheses', 'confidence_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('discovery_hypotheses', 'confidence_delta',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_hypotheses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'proposed'::character varying"))
    op.alter_column('discovery_hypotheses', 'provenance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_hypotheses', 'reddit_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_hypotheses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_sessions', 'current_iteration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('discovery_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_sessions', 'session_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_sessions', 'total_ai_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_discovery_sessions_client_id'), table_name='discovery_sessions')
    op.drop_index(op.f('ix_discovery_sessions_operator_user_id'), table_name='discovery_sessions')
    op.alter_column('epg_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('uq_epg_slots_avatar_date_hobby', 'epg_slots', ['avatar_id', 'plan_date', 'hobby_post_id'], unique=True, postgresql_where=sa.text('hobby_post_id IS NOT NULL'))
    op.create_index('uq_epg_slots_avatar_date_thread', 'epg_slots', ['avatar_id', 'plan_date', 'thread_id'], unique=True, postgresql_where=sa.text('thread_id IS NOT NULL'))
    op.drop_index(op.f('ix_execution_nodes_executor_id'), table_name='execution_nodes')
    op.drop_index(op.f('ix_execution_nodes_is_online'), table_name='execution_nodes')
    op.drop_column('execution_nodes', 'last_dom_health_change')
    op.drop_column('execution_nodes', 'consecutive_failures')
    op.create_index(op.f('ix_execution_tasks_epg_slot_id'), 'execution_tasks', ['epg_slot_id'], unique=False)
    op.create_index('ix_execution_tasks_lifecycle_status', 'execution_tasks', ['task_lifecycle_status'], unique=False)
    op.create_index('ix_execution_tasks_node_id', 'execution_tasks', ['execution_node_id'], unique=False)
    op.drop_constraint(op.f('fk_execution_tasks_execution_node_id'), 'execution_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'execution_tasks', 'execution_nodes', ['execution_node_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hobby_subreddits_post_id', 'hobby_subreddits', ['post_id'], unique=False)
    op.alter_column('karma_snapshots', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('llm_quality_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_llm_quality_snapshots_degradation'), table_name='llm_quality_snapshots')
    op.drop_index(op.f('ix_llm_quality_snapshots_window'), table_name='llm_quality_snapshots')
    op.alter_column('opportunities', 'actual_removal',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plan_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('plan_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_posting_events_avatar_id'), table_name='posting_events')
    op.drop_index(op.f('ix_posting_events_avatar_posted'), table_name='posting_events')
    op.drop_index(op.f('ix_posting_events_outcome'), table_name='posting_events')
    op.drop_index(op.f('ix_posting_events_posted_at'), table_name='posting_events')
    op.drop_index(op.f('ix_reddit_threads_is_locked'), table_name='reddit_threads', postgresql_where='(is_locked = true)')
    op.drop_index(op.f('ix_reddit_threads_reddit_created_at'), table_name='reddit_threads')
    op.create_index('ix_reddit_threads_client_id', 'reddit_threads', ['client_id'], unique=False)
    op.create_index('ix_reddit_threads_created_at', 'reddit_threads', ['created_at'], unique=False)
    op.create_index('ix_reddit_threads_scraped_at', 'reddit_threads', ['scraped_at'], unique=False, postgresql_where=sa.text('is_locked = false'))
    op.create_index('ix_reddit_threads_subreddit_id', 'reddit_threads', ['subreddit_id'], unique=False)
    op.create_index('ix_reddit_threads_subreddit_not_locked', 'reddit_threads', ['subreddit_id'], unique=False, postgresql_where=sa.text('is_locked = false'))
    op.drop_column('reddit_threads', 'strategic')
    op.drop_column('reddit_threads', 'intent')
    op.drop_column('reddit_threads', 'quality')
    op.drop_column('reddit_threads', 'scoring_reasoning')
    op.drop_column('reddit_threads', 'relevance')
    op.create_index('ix_scrape_log_subreddit_name', 'scrape_log', ['subreddit_name'], unique=False)
    op.create_foreign_key(None, 'scrape_log', 'subreddits', ['subreddit_id'], ['id'])
    op.alter_column('strategy_documents', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('strategy_documents_discovery_session_id_fkey'), 'strategy_documents', type_='foreignkey')
    op.drop_column('strategy_documents', 'discovery_session_id')
    op.create_index('ix_thread_scores_client_thread', 'thread_scores', ['client_id', 'thread_id'], unique=False)
    op.alter_column('upsell_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visibility_reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('visibility_reports', 'report_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('visibility_reports', 'generation_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_visibility_reports_session_id'), table_name='visibility_reports')
    op.alter_column('webhook_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('zero_day_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zero_day_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('webhook_events', 'processed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_visibility_reports_session_id'), 'visibility_reports', ['session_id'], unique=False)
    op.alter_column('visibility_reports', 'generation_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('visibility_reports', 'report_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('visibility_reports', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('upsell_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_thread_scores_client_thread', table_name='thread_scores')
    op.add_column('strategy_documents', sa.Column('discovery_session_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('strategy_documents_discovery_session_id_fkey'), 'strategy_documents', 'discovery_sessions', ['discovery_session_id'], ['id'], ondelete='SET NULL')
    op.alter_column('strategy_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategy_documents', 'generated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'scrape_log', type_='foreignkey')
    op.drop_index('ix_scrape_log_subreddit_name', table_name='scrape_log')
    op.add_column('reddit_threads', sa.Column('relevance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reddit_threads', sa.Column('scoring_reasoning', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('reddit_threads', sa.Column('quality', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reddit_threads', sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('reddit_threads', sa.Column('strategic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ix_reddit_threads_subreddit_not_locked', table_name='reddit_threads', postgresql_where=sa.text('is_locked = false'))
    op.drop_index('ix_reddit_threads_subreddit_id', table_name='reddit_threads')
    op.drop_index('ix_reddit_threads_scraped_at', table_name='reddit_threads', postgresql_where=sa.text('is_locked = false'))
    op.drop_index('ix_reddit_threads_created_at', table_name='reddit_threads')
    op.drop_index('ix_reddit_threads_client_id', table_name='reddit_threads')
    op.create_index(op.f('ix_reddit_threads_reddit_created_at'), 'reddit_threads', ['reddit_created_at'], unique=False)
    op.create_index(op.f('ix_reddit_threads_is_locked'), 'reddit_threads', ['is_locked'], unique=False, postgresql_where='(is_locked = true)')
    op.create_index(op.f('ix_posting_events_posted_at'), 'posting_events', [sa.literal_column('posted_at DESC')], unique=False)
    op.create_index(op.f('ix_posting_events_outcome'), 'posting_events', ['outcome'], unique=False)
    op.create_index(op.f('ix_posting_events_avatar_posted'), 'posting_events', ['avatar_id', sa.literal_column('posted_at DESC')], unique=False)
    op.create_index(op.f('ix_posting_events_avatar_id'), 'posting_events', ['avatar_id'], unique=False)
    op.alter_column('plan_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('plan_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('performance_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('opportunities', 'actual_removal',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_llm_quality_snapshots_window'), 'llm_quality_snapshots', ['window_start', 'model', 'operation'], unique=False)
    op.create_index(op.f('ix_llm_quality_snapshots_degradation'), 'llm_quality_snapshots', ['degradation_detected', 'created_at'], unique=False)
    op.alter_column('llm_quality_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('karma_snapshots', 'checked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_hobby_subreddits_post_id', table_name='hobby_subreddits')
    op.drop_constraint(None, 'execution_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_execution_tasks_execution_node_id'), 'execution_tasks', 'execution_nodes', ['execution_node_id'], ['id'])
    op.drop_index('ix_execution_tasks_node_id', table_name='execution_tasks')
    op.drop_index('ix_execution_tasks_lifecycle_status', table_name='execution_tasks')
    op.drop_index(op.f('ix_execution_tasks_epg_slot_id'), table_name='execution_tasks')
    op.add_column('execution_nodes', sa.Column('consecutive_failures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('execution_nodes', sa.Column('last_dom_health_change', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_execution_nodes_is_online'), 'execution_nodes', ['is_online'], unique=False)
    op.create_index(op.f('ix_execution_nodes_executor_id'), 'execution_nodes', ['executor_id'], unique=False)
    op.drop_index('uq_epg_slots_avatar_date_thread', table_name='epg_slots', postgresql_where=sa.text('thread_id IS NOT NULL'))
    op.drop_index('uq_epg_slots_avatar_date_hobby', table_name='epg_slots', postgresql_where=sa.text('hobby_post_id IS NOT NULL'))
    op.alter_column('epg_slots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_discovery_sessions_operator_user_id'), 'discovery_sessions', ['operator_user_id'], unique=False)
    op.create_index(op.f('ix_discovery_sessions_client_id'), 'discovery_sessions', ['client_id'], unique=False)
    op.alter_column('discovery_sessions', 'total_ai_cost_usd',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('discovery_sessions', 'session_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_sessions', 'current_iteration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('discovery_hypotheses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_hypotheses', 'reddit_signals',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_hypotheses', 'provenance',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('discovery_hypotheses', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'proposed'::character varying"))
    op.alter_column('discovery_hypotheses', 'confidence_delta',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('discovery_hypotheses', 'confidence_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.create_index(op.f('ix_discovery_entities_session_id'), 'discovery_entities', ['session_id'], unique=False)
    op.alter_column('discovery_entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('discovery_entities', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'extracted'::character varying"))
    op.alter_column('decision_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_comment_drafts_thread_pending', table_name='comment_drafts', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_comment_drafts_status', table_name='comment_drafts')
    op.drop_index('ix_comment_drafts_created_at', table_name='comment_drafts')
    op.drop_index('ix_comment_drafts_client_status', table_name='comment_drafts')
    op.drop_index('ix_comment_drafts_avatar_status', table_name='comment_drafts')
    op.create_index(op.f('ix_comment_drafts_avatar_status_created'), 'comment_drafts', ['avatar_id', 'status', 'created_at'], unique=False)
    op.alter_column('clients', 'current_onboarding_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_client_subscriptions_client_id'), table_name='client_subscriptions')
    op.create_index(op.f('ix_client_subscriptions_client_id'), 'client_subscriptions', ['client_id'], unique=False)
    op.create_unique_constraint(op.f('client_subscriptions_client_id_key'), 'client_subscriptions', ['client_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('client_subscriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('client_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('uq_client_subreddits_active_name'), 'client_subreddits', [sa.literal_column('lower(subreddit_name::text)')], unique=True, postgresql_where='(is_active = true)')
    op.drop_index('ix_csa_client_active_subreddit', table_name='client_subreddit_assignments')
    op.alter_column('billing_period_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_avatars_pool'), 'avatars', ['pool'], unique=False)
    op.create_index(op.f('ix_avatars_client_ids_gin'), 'avatars', ['client_ids'], unique=False, postgresql_using='gin')
    op.alter_column('avatars', 'delivery_channel',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'email'::character varying"))
    op.drop_index('ix_avatar_presence_avatar_activity', table_name='avatar_subreddit_presence')
    op.create_index(op.f('ix_avatar_presence_avatar_activity'), 'avatar_subreddit_presence', ['avatar_id', sa.literal_column('last_activity_at DESC NULLS LAST')], unique=False)
    op.alter_column('avatar_subreddit_bans', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('avatar_subreddit_bans', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('avatar_subreddit_bans', 'consecutive_deletions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('avatar_subreddit_bans', 'detection_evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('avatar_subreddit_bans', 'banned_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_log_client_action_created'), 'audit_log', ['client_id', 'action', 'created_at'], unique=False)
    op.drop_index('ix_ai_usage_log_operation', table_name='ai_usage_log')
    op.drop_index('ix_ai_usage_log_client_created', table_name='ai_usage_log')
    op.create_index(op.f('ix_ai_usage_log_subreddit_name'), 'ai_usage_log', ['subreddit_name'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_quality_outcome'), 'ai_usage_log', ['quality_outcome'], unique=False)
    op.create_index(op.f('ix_ai_usage_log_avatar_id'), 'ai_usage_log', ['avatar_id'], unique=False)
    op.drop_index('ix_activity_events_type_created', table_name='activity_events')
    op.drop_index('ix_activity_events_client_created', table_name='activity_events')
    op.create_table('avatar_subreddit_compatibility',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('avatar_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subreddit_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mismatch_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_stale', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['avatars.id'], name=op.f('avatar_subreddit_compatibility_avatar_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('avatar_subreddit_compatibility_pkey'))
    )
    op.create_index(op.f('ix_asc_subreddit_score'), 'avatar_subreddit_compatibility', ['subreddit_name', 'score'], unique=False)
    op.create_index(op.f('ix_asc_avatar_subreddit'), 'avatar_subreddit_compatibility', ['avatar_id', 'subreddit_name'], unique=True)
    op.create_table('waitlist_signups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('accounts_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_tier', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('variant_shown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_page', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('waitlist_signups_pkey')),
    sa.UniqueConstraint('email', name=op.f('waitlist_signups_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_waitlist_signups_email'), 'waitlist_signups', ['email'], unique=False)
    op.create_index(op.f('ix_waitlist_signups_created_at'), 'waitlist_signups', ['created_at'], unique=False)
    op.create_table('ab_test_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('variant_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('converted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ab_test_assignments_pkey'))
    )
    op.create_index(op.f('ix_ab_test_assignments_visitor_id'), 'ab_test_assignments', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_ab_test_assignments_test_variant'), 'ab_test_assignments', ['test_name', 'variant_name'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visitor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('page_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('ix_analytics_events_visitor_id'), 'analytics_events', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_type_timestamp'), 'analytics_events', ['event_type', 'timestamp'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('persona_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('voice_profile', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('personas_client_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('personas_pkey'))
    )
    op.create_table('action_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('action_requests_client_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('action_requests_resolved_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('action_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('action_requests_pkey'))
    )
    op.create_index(op.f('ix_action_requests_client_status'), 'action_requests', ['client_id', 'status'], unique=False)
    op.create_index(op.f('ix_action_requests_client_action_status'), 'action_requests', ['client_id', 'action_type', 'status'], unique=False)
    op.create_table('alembic_version_marketing',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_marketing_pkc'))
    )
    op.drop_index(op.f('ix_bug_reports_status'), table_name='bug_reports')
    op.drop_index(op.f('ix_bug_reports_bug_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
