"""Pydantic models for Discovery Engine validation schemas."""

from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field, model_validator


# --- LLM Output Validation Schemas ---


class ExtractedEntity(BaseModel):
    """A single entity extracted from the client brief."""

    name: str = Field(max_length=200)
    category: Literal[
        "product", "audience", "problem", "industry", "competitor", "use_case"
    ]


class EntityExtractionOutput(BaseModel):
    """Validates LLM entity extraction response (3-20 entities)."""

    entities: list[ExtractedEntity] = Field(min_length=3, max_length=20)


class HypothesisItem(BaseModel):
    """A single hypothesis generated by the LLM."""

    statement: str = Field(max_length=1000)
    category: Literal[
        "clients", "partners", "feedback", "recognition", "hiring", "market_research"
    ]
    triggering_entities: list[str] = Field(
        min_length=1, description="Entity IDs or names that triggered this hypothesis"
    )
    reasoning: str = Field(max_length=500)


class HypothesisFormationOutput(BaseModel):
    """Validates LLM hypothesis generation response (3-7 hypotheses)."""

    hypotheses: list[HypothesisItem] = Field(min_length=3, max_length=7)


# --- Reddit Signal Validation ---


class SubredditSignal(BaseModel):
    """A single subreddit's signal data from Reddit research."""

    name: str
    subscribers: int = Field(ge=0)
    posts_30d: int = Field(ge=0)
    avg_engagement: float = Field(ge=0)
    relevance_score: int = Field(ge=0, le=100)


class NoSignalAssessment(BaseModel):
    """Assessment when Reddit has no relevant signal for a hypothesis."""

    cause: Literal["search_too_narrow", "topic_absent"]
    explanation: str
    suggestions: list[str]


class RedditSignalOutput(BaseModel):
    """Validates Reddit research results for a hypothesis."""

    subreddits: list[SubredditSignal] = Field(default_factory=list)
    total_posts_found: int = Field(ge=0)
    avg_engagement: float = Field(ge=0)
    no_signal: NoSignalAssessment | None = None


# --- Visibility Report Content ---


class ReportCommunity(BaseModel):
    """A community entry in the Visibility Report."""

    name: str
    subscribers: int = Field(ge=0)
    daily_posts: int = Field(ge=0)
    relevance: int = Field(ge=0, le=100)
    approach: str


class VisibilityOutcome(BaseModel):
    """A visibility outcome with probability assessment."""

    type: Literal[
        "clients", "partners", "feedback", "recognition", "hiring", "market_research"
    ]
    probability: Literal["high", "medium", "low"]
    reasoning: str


class VisibilityReportContent(BaseModel):
    """Validates the JSONB content structure of a Visibility Report."""

    executive_summary: str
    demand_assessment: str
    communities: list[ReportCommunity]
    discussion_activity: str
    entry_points: list[str]
    competitive_landscape: str
    visibility_outcomes: list[VisibilityOutcome]
    risks_and_limitations: str


# --- Request/Action Schemas ---


class SessionCreateRequest(BaseModel):
    """Validates session creation form input."""

    client_brief: str = Field(min_length=50, max_length=5000)
    prospect_name: str | None = Field(default=None, max_length=200)
    client_id: UUID | None = None


class HypothesisDecision(BaseModel):
    """Validates operator confirm/reject action on a hypothesis."""

    hypothesis_id: UUID
    action: Literal["confirm", "reject"]
    rejection_reason: str | None = Field(default=None, min_length=10, max_length=500)

    @model_validator(mode="after")
    def require_reason_on_reject(self) -> "HypothesisDecision":
        """Rejection reason is required when action is reject."""
        if self.action == "reject" and not self.rejection_reason:
            raise ValueError("rejection_reason is required when action is 'reject'")
        return self
